apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-v3io-auth
  labels:
    app: {{ template "v3io-framesd.name" . }}
    chart: {{ template "v3io-framesd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ include "v3io-configs.fuse.secret" . | indent 2 }}
